version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jurishub_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    image: nhoknj789/jurishub-backend:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/jurishub_db
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  frontend:
    image: nhoknj789/jurishub-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
